export enum PostCategory {
    TECHNOLOGY = 'TECHNOLOGY',
    LIFESTYLE = 'LIFESTYLE',
    HEALTH_FITNESS = 'HEALTH_FITNESS',
    TRAVEL = 'TRAVEL',
    BUSINESS = 'BUSINESS',
    FINANCE = 'FINANCE',
    FOOD_DRINK = 'FOOD_DRINK',
    EDUCATION = 'EDUCATION',
    FASHION_BEAUTY = 'FASHION_BEAUTY',
    ENTERTAINMENT = 'ENTERTAINMENT',
  }
  